#i using google colab 
# -*- coding: utf-8 -*-
"""Copy of Welcome To Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zdeyFSsjb2XH19kB5__pLwikrQl-6AS0
"""

!pip install numpy

!pip install matplotlib

!pip install astropy

!pip install astroquery

"""<b><h1 style="position:center">Untuk 51 Pegasi b</b></h1> <br>
<h3>plot radial velocity toward times</h3>
"""

import numpy as np
import matplotlib.pyplot as plt
M = 1.989*10**30
mas = 1.12*M
mas_error = 0.06

fname = '51 Pegasi RV.txt'
data = np.genfromtxt(fname,skip_header=21,autostrip=True)
jd = data[: , 0]
rv = data[: , 1]
er = data[: , 2]
fig, ax = plt.subplots(figsize=(8,5))
plt.plot(jd,rv,'.')
plt.errorbar(jd, rv, er, fmt=".k")
ax.text(1, -0.3, 'Source data : Marcy et al., 1997, ApJ 481, 926-935', color='red', ha='right', transform=ax.transAxes)
plt.title('RV data for 51 Peg b', y=1.10, fontsize=16, fontweight='bold', ha='center')
plt.xlabel('JD - 2450000')
plt.ylabel('Radial Velocity (m/s)')
plt.tight_layout()
plt.grid()
plt.savefig('a_51Peg.png')
plt.show()

"""<h3>using periodogram lomb-scargle to calculate and plot periode/frequency</h3>


"""

#Lomb-Scargle
import matplotlib.pyplot as plt
from astropy.timeseries import LombScargle

fig, ax = plt.subplots(figsize=(8,5))
ls = LombScargle(jd, rv,er)
frequency,power = ls.autopower()
ls.false_alarm_probability(power.max())
ax.text(1, -0.3, 'Sumber data : Marcy et al., 1997, ApJ 481, 926-935', color='red', ha='right',transform=ax.transAxes)
plt.plot(frequency,power,'k')
plt.title('Lomb-Scargle periodogram for 51 Peg b', y=1.10, fontsize=16,fontweight='bold', ha='center')
plt.xlabel('frequency [days$^{-1}$]')
plt.ylabel('Lomb-Scargle power')
plt.tight_layout()
plt.grid()
plt.savefig('b_51Peg.png')
plt.show()

"""<h3> plot phase radial velocity"""

# find period 
import numpy as np
import matplotlib.pyplot as plt
from astropy.stats import LombScargle
period = 1/frequency[np.argmax(power)]
print("The fit period is %10.5f days" % period)
tfit = np.linspace(0,period,1000)
rvfit = LombScargle(jd,rv,er)
phase = jd % period
fig,ax = plt.subplots(figsize=(10,6))
plt.errorbar(((jd-jd[len(jd)//2])% period)/period, rv, yerr=er, fmt="b.")
plt.title('phase RV data for 51 Peg b', fontsize=16, fontweight='bold', ha='center', y=1.10)
plt.xlim(0, 1)
plt.ylim(-110, 110)
plt.xlabel('Phase')
ax.text(1, -0.13, 'Source data : Marcy et al., 1997, ApJ 481, 926-935', color='red', ha='right',transform=ax.transAxes)
plt.ylabel('Radial Velocity (m/s)')
plt.annotate('Period = {0:.7f} days'.format(period), xy=(1,0), xycoords='axes fraction',
             xytext=(-5,5), textcoords='offset points', ha='right', va='bottom', fontsize=12)
plt.savefig('c_51Peg.png')
plt.grid()
plt.show()

"""<h3> d. result fitting </h3>"""

# find period 
import matplotlib.pyplot as plt
period = 1/frequency[np.argmax(power)]
print("The fit period is %10.7f days" % period)
# calculate model fit based on period 
tfit = np.linspace(0,period,1000)
rvfit = LombScargle(jd,rv,er).model(tfit,1/period)
K = 0.5*(np.max(rvfit)-np.min(rvfit))
print("The fit semi-amplitude is %10.5f m/s" % K)
# phase the data and plot it with the fit
phase = jd % period
fig,ax = plt.subplots(figsize=(10,6))
ax.errorbar(phase,rv,er,fmt=".k")
ax.plot(tfit,rvfit,"-k")
ax.text(1, -0.1, 'Source data : Marcy et al., 1997, ApJ 481, 926-935',color='red',ha='right',transform=ax.transAxes)
plt.title('phase RV data for 51 Peg b',fontsize=16,fontweight='bold',ha='center',y=1.10)
plt.xlabel('Phase')
plt.ylabel('Radial Velocity (m/s)')
plt.xlim(0,4)
plt.ylim(-110, 110)
plt.grid()
plt.savefig('d_51Peg.png')
plt.show()

"""<b><h1>for HD 3651 b <b><h1><br>
<h3>a. plot radial velocity toward times in Julian Day

"""

import numpy as np
import matplotlib.pyplot as plt
M_J = 1.898*10**27
mas = 0.23*M_J
rav_error = 0.02

fname = 'HD 3651 b.txt'
data = np.genfromtxt(fname,skip_header=21,autostrip=True)
jd = data[: , 0]
rv = data[: , 1]
er = data[: , 2]
fig,ax = plt.subplots(figsize=(8,5))
plt.plot(jd,rv,'.')
plt.errorbar(jd, rv, er,fmt=".k")
plt.title('RV data for HD 3651 b',fontsize=16,fontweight='bold',ha='center',y=1.10)
plt.xlabel('JD - 2440000')
ax.text(1, -0.2, 'Source data: Fischer et al., 2003, ApJ 590, 1081-1087',color='red',ha='right',transform=ax.transAxes)
plt.ylabel('Radial Velocity (m/s)')
plt.savefig('a_HD3651.png')
plt.grid()
plt.show()

"""<h3>b.using periodogram lomb-scargle to calculate period and plot
"""

#Lomb-Scargle
import matplotlib.pyplot as plt
from astropy.timeseries import LombScargle

fig, ax = plt.subplots(figsize=(8,5))
ls = LombScargle(jd, rv,er)
frequency,power = ls.autopower()
ls.false_alarm_probability(power.max())
ax.text(1, -0.3, 'Source data : Marcy et al., 1997, ApJ 481, 926-935', color='red', ha='right',transform=ax.transAxes)
plt.plot(frequency,power,'k')
plt.title('Lomb-Scargle periodogram for HD 3651 b', y=1.10, fontsize=16,fontweight='bold', ha='center')
plt.xlabel('frequency [days$^{-1}$]')
plt.ylabel('Lomb-Scargle power')
plt.tight_layout()
plt.grid()
plt.savefig('b_HD3651.png')
plt.show()

"""<h3> c. plot phase radial velocity </h3>"""

# find period 
import numpy as np
import matplotlib.pyplot as plt
from astropy.stats import LombScargle
period = 1/frequency[np.argmax(power)]
print("The fit period is %10.5f days" % period)
tfit = np.linspace(0,period,1000)
rvfit = LombScargle(jd,rv,er)
phase = jd % period
fig,ax = plt.subplots(figsize=(10,6))
plt.errorbar(((jd-jd[len(jd)//2])% period)/period, rv, yerr=er, fmt="b.")
plt.title('phase RV data for HD 3651 b', fontsize=16, fontweight='bold', ha='center', y=1.10)
plt.xlim(0, 1)
plt.ylim(-40, 40)
plt.xlabel('Phase')
ax.text(1, -0.13, 'Source data : Fischer et al., 2003, ApJ 590, 1081-1087', color='red', ha='right',transform=ax.transAxes)
plt.ylabel('Radial Velocity (m/s)')
plt.annotate('Period = {0:.7f} days'.format(period), xy=(1,0), xycoords='axes fraction',
             xytext=(-5,5), textcoords='offset points', ha='right', va='bottom', fontsize=12)
plt.savefig('c_HD 3651.png')
plt.grid()
plt.show()

"""<h3> d. result fitting </h3>"""

# find period 
import matplotlib.pyplot as plt
period = 1/frequency[np.argmax(power)]
print("The fit period is %10.7f days" % period)
# calculate model fit based on period 
tfit = np.linspace(0,period,1000)
rvfit = LombScargle(jd,rv,er).model(tfit,1/period)
# phase the data and plot it with the fit
phase = jd % period
fig,ax = plt.subplots(figsize=(10,6))
ax.errorbar(phase,rv,er,fmt=".k")
ax.plot(tfit,rvfit,"-b")
ax.text(1, -0.13, 'Source data: Fischer et al., 2003, ApJ 590, 1081-1087',color='red',ha='right',transform=ax.transAxes)
plt.title('phase RV data for HD 3651 b',fontsize=16,fontweight='bold',ha='center',y=1.10)
plt.xlabel('Phase')
plt.ylabel('Radial Velocity (m/s)')
plt.savefig('d_HD3651.png')
plt.ylim(-40, 40)
plt.grid()
plt.show()
